### ISSUE TITLE
Keep only one lockfile for the project

### ISSUE THREAD

**Issue by karmek-k** [aldy-san/zero-neko#14]
As I can see, there are two lockfiles in this repo:

- `package-lock.json`
- `yarn.lock`

This kind of defeats the purpose of a lockfile, as contributors may have wrong package versions depending on whether they use `npm` or `yarn`. 

Which dependency manager should be used for this project? (I used `npm` because `package-lock.json` was updated more recently.)

**Comment by aldy-san** [comment]
aaa, i dont know about that before, thank you. so, is it okay to just delete `yarn.lock` file?

**Comment by karmek-k** [comment]
Yes, delete it if you plan on using `npm` (make sure to tell the contributors about the preferred dependency manager).

**Comment by aldy-san** [comment]
oh, ok thanks..
