### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by KarishmaVanwari** [aldy-san/zero-neko#6]
Adding a custom scrollbar would improve the look of the website.

**Comment by KarishmaVanwari** [comment]
Hey @aldy-san can I work on this issue as a part of Hacktoberfest 2021, if it's okay with you?
Also, you can let me know your colour preferences, if any.

**Comment by aldy-san** [comment]
sure you can. maybe, this color is good #f76d70, or if you have another idea, its ok.

**Comment by KarishmaVanwari** [comment]
Okay. Could you add hacktoberfest label ?

**Comment by aldy-san** [comment]
yes sure

**Comment by KarishmaVanwari** [comment]
@aldy-san do have a look at #10
