### ISSUE TITLE
Pairing Kana game allows the same script to be picked twice

### ISSUE THREAD

**Issue by karmek-k** [aldy-san/zero-neko#7]
Hello!

I have found this project via Hacktoberfest. I'm a Japanese language learner and I really like the idea of learning by games.

Regarding the issue, it is possible to pick romaji and romaji (or hiragana and hiragana, or katakana and katakana) in the Pairing Kana game.
Doing it results in this:

![Przechwycenie obrazu ekranu_2021-10-03_14-11-51](https://user-images.githubusercontent.com/33288445/135753256-78da75f5-5e7f-4b0a-80d2-1cc76f931e6f.png)

I think that the easiest solution is to simply prevent the user from starting the game in this situation. Can I have this issue assigned to me? :)

**Comment by aldy-san** [comment]
Hello, im happy to meet another japanese language learner too.

sure. i will assign this issue to you.
